/*
 * Copyright (c) 2017, NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_IMX_CCM_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_IMX_CCM_H_

#define IMX_CCM_CORESYS_CLK		0
#define IMX_CCM_PLATFORM_CLK		1
#define IMX_CCM_BUS_CLK			2
#define IMX_CCM_LPUART_CLK		3
#define IMX_CCM_LPI2C_CLK		4
#define IMX_CCM_LPSPI_CLK		5
#define IMX_CCM_USDHC1_CLK		6
#define IMX_CCM_USDHC2_CLK		7
#define IMX_CCM_EDMA_CLK		8
#define IMX_CCM_UART_CLK		9
#define IMX_CCM_CAN_CLK			10
#define IMX_CCM_GPT_CLK			11
#define IMX_CCM_SAI1_CLK		12
#define IMX_CCM_SAI2_CLK		13
#define IMX_CCM_SAI3_CLK		14
#define IMX_CCM_PWM_CLK			15
#define IMX_CCM_UART2_CLK		16
#define IMX_CCM_UART3_CLK		17
#define IMX_CCM_UART4_CLK		18
#define IMX_CCM_I2C1_CLK		19
#define IMX_CCM_I2C2_CLK		20
#define IMX_CCM_I2C3_CLK		21
#define IMX_CCM_I2C4_CLK		22
#define IMX_CCM_I2C5_CLK		23
#define IMX_CCM_I2C6_CLK		24
#define IMX_CCM_GPT1_CLK		25
#define IMX_CCM_GPT2_CLK		26
#define IMX_CCM_GPT3_CLK		27
#define IMX_CCM_GPT4_CLK		28
#define IMX_CCM_GPT5_CLK		29
#define IMX_CCM_GPT6_CLK		30
#define IMX_CCM_ECSPI1_CLK		31
#define IMX_CCM_ECSPI2_CLK		32
#define IMX_CCM_ECSPI3_CLK		33
#define IMX_CCM_CAN1_CLK		34
#define IMX_CCM_CAN2_CLK		35
#define IMX_CCM_PWM1_CLK		36
#define IMX_CCM_PWM2_CLK		37
#define IMX_CCM_PWM3_CLK		38
#define IMX_CCM_PWM4_CLK		39
#define IMX_CCM_WDOG1_CLK		40
#define IMX_CCM_WDOG2_CLK		41
#define IMX_CCM_WDOG3_CLK		42
#define IMX_CCM_FLEXSPI_CLK		43

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_IMX_CCM_H_ */
